# Generated by Django 3.2.14 on 2022-09-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=60, null=True)),
                ('employement_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Freelancing', 'Freelancing'), ('Contract', 'Contract')], default='Full time', max_length=50)),
                ('experience', models.CharField(choices=[('Fresher (less than one year)', 'Fresher (less than one year)'), ('1 year', '1 year'), ('2 years', '2 years'), ('3 years', '3 years'), ('4 years', '4 years'), ('5 years', '5 years'), ('6 years', '6 years'), ('7 years', '7 years'), ('8 years', '8 years'), ('9 years', '9 years'), ('10 years', '10 years'), ('11 years', '11 years'), ('12 years', '12 years'), ('13 years', '13 years'), ('14 years', '14 years'), ('15 years', '15 years'), ('16 years', '16 years'), ('17 years', '17 years'), ('18 years', '18 years'), ('19 years', '19 years'), ('20 years', '20 years'), ('21 years', '21 years'), ('22 years', '22 years'), ('23 years', '23 years'), ('24 years', '24 years'), ('25 years', '25 years'), ('26 years', '26 years'), ('27 years', '27 years'), ('28 years', '28 years'), ('29 years', '29 years'), ('30 years', '30 years')], max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('no_of_openings', models.PositiveSmallIntegerField()),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('job_applied_count', models.PositiveIntegerField(default=0)),
                ('skills', models.CharField(max_length=50)),
                ('publish', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-publish', '-published_at', django.db.models.functions.comparison.Cast('visit_count', output_field=models.IntegerField())],
            },
        ),
    ]
