# Generated by Django 3.2.14 on 2022-09-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_jobapplicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='applicant',
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
