# Generated by Django 3.2.14 on 2022-09-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20220909_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
    ]
