# Generated by Django 3.2.14 on 2022-09-10 07:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobapplicant_is_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_applied',
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
