# Generated by Django 3.2.14 on 2022-09-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Keyskills',
            field=models.CharField(default='programming', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(default='It', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='role_category',
            field=models.CharField(default='developer', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Italy', 'Italy'), ('Switzerland', 'Switzerland'), ('USA', 'USA')], default='India', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
