# Generated by Django 3.2.14 on 2022-09-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20220913_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='role_category',
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com/in/dilip-sapkota-6547b4114/', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='message',
            field=models.TextField(default='i am looking for full stack developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='qualitative_skills',
            field=models.CharField(default='problem solving', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='subject',
            field=models.CharField(default='Django Developer', max_length=200),
            preserve_default=False,
        ),
    ]
