# Generated by Django 3.2.14 on 2022-09-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_keyskills_job_functional_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='city',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='skillset_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
    ]
