# Generated by Django 3.2.14 on 2022-09-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20220915_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skillset_required',
        ),
    ]
