# Generated by Django 3.2.14 on 2022-09-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_skillset_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skillset_required',
        ),
        migrations.AddField(
            model_name='job',
            name='skillset_required',
            field=models.ManyToManyField(to='job.Skill'),
        ),
    ]
