# Generated by Django 3.2.14 on 2022-09-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20220916_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='skillset_required',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='added',
        ),
        migrations.AddField(
            model_name='skill',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.job'),
            preserve_default=False,
        ),
    ]
