# Generated by Django 3.2.14 on 2022-09-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_auto_20220916_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job Post', 'verbose_name_plural': 'Job Posts'},
        ),
    ]
